//! The Material icon theme, embedded in the binary.
//!
//! Generated by `scripts/import-material-icons.py` from
//! `third_party/material-icon-theme/` — do not edit by hand. Re-run that
//! script to update the pack.
//!
//! The manifest is embedded as text and parsed at load time like any
//! installed plugin's, so a broken vendored manifest is a load error on
//! the Plugins page rather than a panic at startup.

use crate::BuiltinPlugin;

/// `("icons/<id>.svg", bytes)` for each id, plus the pack itself.
///
/// A macro over bare ids rather than one `include_bytes!` line per file:
/// 1251 files, and the paths are all the same but for the id.
macro_rules! icon_files {
    ($($id:literal)*) => {
        &[
            (
                "pack.toml",
                include_bytes!("../../../third_party/material-icon-theme/pack.toml"),
            ),
            $((
                concat!("icons/", $id, ".svg"),
                include_bytes!(concat!(
                    "../../../third_party/material-icon-theme/icons/",
                    $id,
                    ".svg"
                )),
            ),)*
        ]
    };
}

/// The built-in Markdown preview, first-party rather than vendored — there
/// is no upstream package to import and re-run a script over, unlike the
/// Material icon theme above, so `crates/plugin-host/builtin/` rather than
/// `third_party/`. It contributes no files through the plugin asset seam:
/// its font and its renderer are compiled into `markdown-preview` directly
/// (crate M4), because a font is the renderer's implementation detail and
/// not something a `previews` contribution describes.
pub(crate) const MARKDOWN_PREVIEW: BuiltinPlugin = BuiltinPlugin {
    manifest: include_str!("../builtin/markdown-preview/plugin.toml"),
    files: &[],
};

/// C# support via `csharp-ls`, first-party like the Markdown preview above:
/// a `language-servers` contribution needs no `[wasm]` component or
/// packaged files either, since the server itself is a native process on
/// `PATH` that the host launches, never bundled.
pub(crate) const CSHARP: BuiltinPlugin = BuiltinPlugin {
    manifest: include_str!("../builtin/csharp/plugin.toml"),
    files: &[],
};

/// PHPStan and PHP_CodeSniffer support (the PHP tooling plan's C1), first-
/// party like C# above: an `analyzers` contribution needs no `[wasm]`
/// component either, since both tools are native processes on `PATH` (or
/// under the project's own `vendor/bin`) that the host launches, never
/// bundled.
pub(crate) const PHP_TOOLS: BuiltinPlugin = BuiltinPlugin {
    manifest: include_str!("../builtin/php-tools/plugin.toml"),
    files: &[],
};

/// The three colour themes that used to be hardcoded in `ui-shell`'s
/// `theme.cpp` and `syntax-core`'s `theme.rs`, first-party like the
/// Markdown preview above: a `color-themes` contribution needs no `[wasm]`
/// component either, just the three theme files it points `path` at.
pub(crate) const CORE_THEMES: BuiltinPlugin = BuiltinPlugin {
    manifest: include_str!("../builtin/core-themes/plugin.toml"),
    files: &[
        (
            "dark.toml",
            include_bytes!("../builtin/core-themes/dark.toml"),
        ),
        (
            "light.toml",
            include_bytes!("../builtin/core-themes/light.toml"),
        ),
        (
            "vscode-dark.toml",
            include_bytes!("../builtin/core-themes/vscode-dark.toml"),
        ),
    ],
};

/// The nine `github-vscode-theme` (Primer) colour themes, vendored like
/// the Material icon theme above: `scripts/import-vscode-theme.py`
/// generates `third_party/github-vscode-theme/themes/*.toml` from the
/// upstream VS Code theme JSON, and this constant just embeds the result —
/// nine files is small enough that, unlike the 1251-icon macro above,
/// listing them inline needs no packing trick.
pub(crate) const GITHUB_VSCODE_THEME: BuiltinPlugin = BuiltinPlugin {
    manifest: include_str!("../../../third_party/github-vscode-theme/plugin.toml"),
    files: &[
        (
            "themes/light-default.toml",
            include_bytes!("../../../third_party/github-vscode-theme/themes/light-default.toml"),
        ),
        (
            "themes/light-high-contrast.toml",
            include_bytes!(
                "../../../third_party/github-vscode-theme/themes/light-high-contrast.toml"
            ),
        ),
        (
            "themes/light-colorblind.toml",
            include_bytes!("../../../third_party/github-vscode-theme/themes/light-colorblind.toml"),
        ),
        (
            "themes/dark-default.toml",
            include_bytes!("../../../third_party/github-vscode-theme/themes/dark-default.toml"),
        ),
        (
            "themes/dark-high-contrast.toml",
            include_bytes!(
                "../../../third_party/github-vscode-theme/themes/dark-high-contrast.toml"
            ),
        ),
        (
            "themes/dark-colorblind.toml",
            include_bytes!("../../../third_party/github-vscode-theme/themes/dark-colorblind.toml"),
        ),
        (
            "themes/dark-dimmed.toml",
            include_bytes!("../../../third_party/github-vscode-theme/themes/dark-dimmed.toml"),
        ),
        (
            "themes/light.toml",
            include_bytes!("../../../third_party/github-vscode-theme/themes/light.toml"),
        ),
        (
            "themes/dark.toml",
            include_bytes!("../../../third_party/github-vscode-theme/themes/dark.toml"),
        ),
    ],
};

// The id list is packed by line width, which rustfmt would otherwise
// unpack to one per line and undo the point of the macro.
#[rustfmt::skip]
pub(crate) const MATERIAL_ICON_THEME: BuiltinPlugin = BuiltinPlugin {
    manifest: include_str!("../../../third_party/material-icon-theme/plugin.toml"),
    files: icon_files![
        "3d" "abap" "abc" "actionscript" "ada" "adobe-illustrator" "adobe-illustrator_light"
        "adobe-photoshop" "adobe-photoshop_light" "adobe-swc" "adonis" "advpl" "advpl-include"
        "advpl-ptm" "advpl-tlpp" "agent" "ahk2" "amplify" "android" "angular"
        "angular-component" "angular-directive" "angular-guard" "angular-interceptor"
        "angular-pipe" "angular-resolver" "angular-service" "antlr" "apiblueprint" "apollo"
        "applescript" "apps-script" "appveyor" "appwrite" "architecture" "arduino" "asciidoc"
        "assembly" "astro" "astro-config" "astyle" "audio" "aurelia" "authors" "auto"
        "auto_light" "autohotkey" "autoit" "azure" "azure-pipelines" "babel" "ballerina"
        "bashly" "bashly-hook" "bashly-settings" "bashly-settings_light" "bashly-strings"
        "bashly-strings_light" "bazel" "bbx" "beancount" "bench-js" "bench-jsx" "bench-ts"
        "bibliography" "bibtex-style" "bicep" "biome" "bitbucket" "bithound" "blender" "blink"
        "blink_light" "blitz" "bower" "brainfuck" "browserlist" "browserlist_light" "bruno"
        "buck" "bucklescript" "buildkite" "bun" "bun_light" "c" "c3" "cabal" "caddy" "cadence"
        "cairo" "cake" "capacitor" "capnp" "cbx" "cds" "certificate" "changelog" "chess"
        "chess_light" "chromatic" "chrome" "circleci" "circleci_light" "citation" "clangd"
        "claude" "cline" "clojure" "cloudfoundry" "cmake" "coala" "cobol" "coconut"
        "code-climate" "code-climate_light" "codecov" "codeowners" "coderabbit-ai" "coffee"
        "coldfusion" "coloredpetrinets" "command" "commitizen" "commitlint" "concourse"
        "conduct" "console" "container" "contentlayer" "context" "contributing" "controller"
        "copilot" "copilot_light" "cpp" "craco" "credits" "crystal" "crystal_light" "csharp"
        "css" "css-map" "cucumber" "cuda" "cue" "cursor" "cursor_light" "cypress" "d" "dart"
        "dart_generated" "database" "deepsource" "denizenscript" "deno" "deno_light"
        "dependabot" "dependencies-update" "dhall" "diff" "dinophp" "disc" "django" "dll"
        "docker" "doctex" "doctex-installer" "document" "dotjs" "drawio" "drizzle" "drone"
        "drone_light" "dtx" "duc" "dune" "edge" "editorconfig" "ejs" "elixir" "elm" "email"
        "ember" "epub" "erlang" "esbuild" "eslint" "excalidraw" "exe" "expo" "expo_light"
        "fastlane" "favicon" "figma" "file" "firebase" "flash" "flow" "folder" "folder-admin"
        "folder-admin-open" "folder-android" "folder-android-open" "folder-angular"
        "folder-angular-open" "folder-animation" "folder-animation-open" "folder-ansible"
        "folder-ansible-open" "folder-api" "folder-api-open" "folder-apollo"
        "folder-apollo-open" "folder-app" "folder-app-open" "folder-appwrite"
        "folder-appwrite-open" "folder-archive" "folder-archive-open" "folder-assembly"
        "folder-assembly-open" "folder-astro" "folder-astro-open" "folder-atom"
        "folder-atom-open" "folder-attachment" "folder-attachment-open" "folder-audio"
        "folder-audio-open" "folder-aurelia" "folder-aurelia-open" "folder-aws"
        "folder-aws-open" "folder-azure-pipelines" "folder-azure-pipelines-open" "folder-backup"
        "folder-backup-open" "folder-base" "folder-base-open" "folder-batch" "folder-batch-open"
        "folder-benchmark" "folder-benchmark-open" "folder-bibliography"
        "folder-bibliography-open" "folder-bicep" "folder-bicep-open" "folder-blender"
        "folder-blender-open" "folder-bloc" "folder-bloc-open" "folder-bower"
        "folder-bower-open" "folder-buildkite" "folder-buildkite-open" "folder-cart"
        "folder-cart-open" "folder-changesets" "folder-changesets-open" "folder-ci"
        "folder-ci-open" "folder-circleci" "folder-circleci-open" "folder-class"
        "folder-class-open" "folder-claude" "folder-claude-open" "folder-client"
        "folder-client-open" "folder-cline" "folder-cline-open" "folder-cloud-functions"
        "folder-cloud-functions-open" "folder-cloudflare" "folder-cloudflare-open"
        "folder-cluster" "folder-cluster-open" "folder-cobol" "folder-cobol-open"
        "folder-command" "folder-command-open" "folder-components" "folder-components-open"
        "folder-config" "folder-config-open" "folder-connection" "folder-connection-open"
        "folder-console" "folder-console-open" "folder-constant" "folder-constant-open"
        "folder-container" "folder-container-open" "folder-content" "folder-content-open"
        "folder-context" "folder-context-open" "folder-contract" "folder-contract-open"
        "folder-controller" "folder-controller-open" "folder-core" "folder-core-open"
        "folder-coverage" "folder-coverage-open" "folder-css" "folder-css-open" "folder-cue"
        "folder-cue-open" "folder-cursor" "folder-cursor-open" "folder-cursor-open_light"
        "folder-cursor_light" "folder-custom" "folder-custom-open" "folder-cypress"
        "folder-cypress-open" "folder-dal" "folder-dal-open" "folder-dart" "folder-dart-open"
        "folder-database" "folder-database-open" "folder-debug" "folder-debug-open"
        "folder-decorators" "folder-decorators-open" "folder-delta" "folder-delta-open"
        "folder-deprecated" "folder-deprecated-open" "folder-desktop" "folder-desktop-open"
        "folder-development" "folder-development-open" "folder-directive"
        "folder-directive-open" "folder-dist" "folder-dist-open" "folder-docker"
        "folder-docker-open" "folder-docs" "folder-docs-open" "folder-download"
        "folder-download-open" "folder-drizzle" "folder-drizzle-open" "folder-dump"
        "folder-dump-open" "folder-eas" "folder-eas-open" "folder-element" "folder-element-open"
        "folder-enum" "folder-enum-open" "folder-environment" "folder-environment-open"
        "folder-error" "folder-error-open" "folder-eslint" "folder-eslint-open" "folder-event"
        "folder-event-open" "folder-examples" "folder-examples-open" "folder-expo"
        "folder-expo-open" "folder-export" "folder-export-open" "folder-fastlane"
        "folder-fastlane-open" "folder-favicon" "folder-favicon-open" "folder-features"
        "folder-features-open" "folder-filter" "folder-filter-open" "folder-firebase"
        "folder-firebase-open" "folder-firestore" "folder-firestore-open" "folder-flow"
        "folder-flow-open" "folder-flutter" "folder-flutter-open" "folder-font"
        "folder-font-open" "folder-forgejo" "folder-forgejo-open" "folder-form"
        "folder-form-open" "folder-functions" "folder-functions-open" "folder-gamemaker"
        "folder-gamemaker-open" "folder-gemini-ai" "folder-gemini-ai-open" "folder-generator"
        "folder-generator-open" "folder-gh-workflows" "folder-gh-workflows-open" "folder-git"
        "folder-git-open" "folder-gitea" "folder-gitea-open" "folder-gitea-workflows"
        "folder-gitea-workflows-open" "folder-github" "folder-github-open" "folder-gitlab"
        "folder-gitlab-open" "folder-global" "folder-global-open" "folder-go" "folder-go-open"
        "folder-godot" "folder-godot-open" "folder-gradle" "folder-gradle-open" "folder-graphql"
        "folder-graphql-open" "folder-guard" "folder-guard-open" "folder-gulp"
        "folder-gulp-open" "folder-helm" "folder-helm-open" "folder-helper" "folder-helper-open"
        "folder-home" "folder-home-open" "folder-hook" "folder-hook-open" "folder-husky"
        "folder-husky-open" "folder-i18n" "folder-i18n-open" "folder-images"
        "folder-images-open" "folder-import" "folder-import-open" "folder-include"
        "folder-include-open" "folder-input" "folder-input-open" "folder-instructions"
        "folder-instructions-open" "folder-intellij" "folder-intellij-open"
        "folder-intellij-open_light" "folder-intellij_light" "folder-interceptor"
        "folder-interceptor-open" "folder-interface" "folder-interface-open" "folder-ios"
        "folder-ios-open" "folder-java" "folder-java-open" "folder-javascript"
        "folder-javascript-open" "folder-jinja" "folder-jinja-open" "folder-jinja-open_light"
        "folder-jinja_light" "folder-job" "folder-job-open" "folder-json" "folder-json-open"
        "folder-jupyter" "folder-jupyter-open" "folder-keys" "folder-keys-open" "folder-kotlin"
        "folder-kotlin-open" "folder-kubernetes" "folder-kubernetes-open" "folder-kusto"
        "folder-kusto-open" "folder-layout" "folder-layout-open" "folder-lefthook"
        "folder-lefthook-open" "folder-less" "folder-less-open" "folder-lib" "folder-lib-open"
        "folder-license" "folder-license-open" "folder-link" "folder-link-open" "folder-linux"
        "folder-linux-open" "folder-liquibase" "folder-liquibase-open" "folder-log"
        "folder-log-open" "folder-lottie" "folder-lottie-open" "folder-lua" "folder-lua-open"
        "folder-luau" "folder-luau-open" "folder-macos" "folder-macos-open" "folder-mail"
        "folder-mail-open" "folder-mappings" "folder-mappings-open" "folder-markdown"
        "folder-markdown-open" "folder-mercurial" "folder-mercurial-open" "folder-messages"
        "folder-messages-open" "folder-meta" "folder-meta-open" "folder-metro"
        "folder-metro-open" "folder-middleware" "folder-middleware-open" "folder-migrations"
        "folder-migrations-open" "folder-mjml" "folder-mjml-open" "folder-mobile"
        "folder-mobile-open" "folder-mock" "folder-mock-open" "folder-mojo" "folder-mojo-open"
        "folder-molecule" "folder-molecule-open" "folder-moon" "folder-moon-open"
        "folder-netlify" "folder-netlify-open" "folder-next" "folder-next-open" "folder-nginx"
        "folder-nginx-open" "folder-ngrx-actions" "folder-ngrx-actions-open"
        "folder-ngrx-effects" "folder-ngrx-effects-open" "folder-ngrx-entities"
        "folder-ngrx-entities-open" "folder-ngrx-reducer" "folder-ngrx-reducer-open"
        "folder-ngrx-selectors" "folder-ngrx-selectors-open" "folder-ngrx-state"
        "folder-ngrx-state-open" "folder-ngrx-store" "folder-ngrx-store-open" "folder-node"
        "folder-node-open" "folder-nuxt" "folder-nuxt-open" "folder-obsidian"
        "folder-obsidian-open" "folder-open" "folder-opencode" "folder-opencode-open"
        "folder-organism" "folder-organism-open" "folder-other" "folder-other-open"
        "folder-packages" "folder-packages-open" "folder-pdf" "folder-pdf-open" "folder-pdm"
        "folder-pdm-open" "folder-php" "folder-php-open" "folder-phpmailer"
        "folder-phpmailer-open" "folder-pipe" "folder-pipe-open" "folder-plastic"
        "folder-plastic-open" "folder-plugin" "folder-plugin-open" "folder-policy"
        "folder-policy-open" "folder-postman" "folder-postman-open" "folder-powershell"
        "folder-powershell-open" "folder-prisma" "folder-prisma-open" "folder-private"
        "folder-private-open" "folder-project" "folder-project-open" "folder-prompts"
        "folder-prompts-open" "folder-proto" "folder-proto-open" "folder-public"
        "folder-public-open" "folder-python" "folder-python-open" "folder-pytorch"
        "folder-pytorch-open" "folder-quasar" "folder-quasar-open" "folder-queue"
        "folder-queue-open" "folder-r" "folder-r-open" "folder-react-components"
        "folder-react-components-open" "folder-redis" "folder-redis-open" "folder-redux-actions"
        "folder-redux-actions-open" "folder-redux-reducer" "folder-redux-reducer-open"
        "folder-redux-selector" "folder-redux-selector-open" "folder-redux-store"
        "folder-redux-store-open" "folder-redux-toolkit" "folder-redux-toolkit-open"
        "folder-repository" "folder-repository-open" "folder-resolver" "folder-resolver-open"
        "folder-resource" "folder-resource-open" "folder-review" "folder-review-open"
        "folder-robot" "folder-robot-open" "folder-root" "folder-root-open" "folder-routes"
        "folder-routes-open" "folder-rules" "folder-rules-open" "folder-rust" "folder-rust-open"
        "folder-salt" "folder-salt-open" "folder-sandbox" "folder-sandbox-open" "folder-sass"
        "folder-sass-open" "folder-scala" "folder-scala-open" "folder-scons" "folder-scons-open"
        "folder-scrap" "folder-scrap-open" "folder-scripts" "folder-scripts-open"
        "folder-secure" "folder-secure-open" "folder-seeders" "folder-seeders-open"
        "folder-server" "folder-server-open" "folder-serverless" "folder-serverless-open"
        "folder-shader" "folder-shader-open" "folder-shared" "folder-shared-open"
        "folder-simulations" "folder-simulations-open" "folder-skills" "folder-skills-open"
        "folder-snapcraft" "folder-snapcraft-open" "folder-snippet" "folder-snippet-open"
        "folder-src" "folder-src-open" "folder-src-tauri" "folder-src-tauri-open" "folder-stack"
        "folder-stack-open" "folder-stencil" "folder-stencil-open" "folder-store"
        "folder-store-open" "folder-storybook" "folder-storybook-open" "folder-stylus"
        "folder-stylus-open" "folder-sublime" "folder-sublime-open" "folder-supabase"
        "folder-supabase-open" "folder-svelte" "folder-svelte-open" "folder-svg"
        "folder-svg-open" "folder-syntax" "folder-syntax-open" "folder-target"
        "folder-target-open" "folder-taskfile" "folder-taskfile-open" "folder-tasks"
        "folder-tasks-open" "folder-television" "folder-television-open" "folder-temp"
        "folder-temp-open" "folder-template" "folder-template-open" "folder-terraform"
        "folder-terraform-open" "folder-test" "folder-test-open" "folder-theme"
        "folder-theme-open" "folder-toc" "folder-toc-open" "folder-tools" "folder-tools-open"
        "folder-trash" "folder-trash-open" "folder-trigger" "folder-trigger-open"
        "folder-turborepo" "folder-turborepo-open" "folder-typescript" "folder-typescript-open"
        "folder-ui" "folder-ui-open" "folder-unity" "folder-unity-open" "folder-update"
        "folder-update-open" "folder-upload" "folder-upload-open" "folder-utils"
        "folder-utils-open" "folder-vercel" "folder-vercel-open" "folder-verdaccio"
        "folder-verdaccio-open" "folder-video" "folder-video-open" "folder-views"
        "folder-views-open" "folder-vm" "folder-vm-open" "folder-vscode" "folder-vscode-open"
        "folder-vue" "folder-vue-directives" "folder-vue-directives-open" "folder-vue-open"
        "folder-vuepress" "folder-vuepress-open" "folder-vuex-store" "folder-vuex-store-open"
        "folder-wakatime" "folder-wakatime-open" "folder-webpack" "folder-webpack-open"
        "folder-windows" "folder-windows-open" "folder-wordpress" "folder-wordpress-open"
        "folder-yarn" "folder-yarn-open" "folder-zeabur" "folder-zeabur-open" "folder-zed"
        "folder-zed-open" "font" "forth" "fortran" "foxpro" "freemarker" "fsharp" "fusebox"
        "gamemaker" "garden" "gatsby" "gcp" "gemfile" "gemini" "gemini-ai" "git"
        "github-actions-workflow" "github-sponsors" "gitlab" "gitpod" "gleam" "gnuplot" "go"
        "go-mod" "go_gopher" "godot" "godot-assets" "google" "gradle" "grafana-alloy" "grain"
        "graphcool" "graphql" "gridsome" "groovy" "grunt" "gulp" "h" "hack" "hadolint" "haml"
        "handlebars" "happo" "hardhat" "harmonix" "haskell" "haxe" "hcl" "hcl_light" "helm"
        "heroku" "hex" "hip" "histoire" "hjson" "horusec" "hosts" "hosts_light" "hpp" "html"
        "http" "huff" "huff_light" "hurl" "husky" "i18n" "idris" "ifanr-cloud" "image" "imba"
        "installation" "instructions" "ionic" "istanbul" "jar" "java" "javaclass" "javascript"
        "javascript-map" "jenkins" "jest" "jinja" "jinja_light" "jsconfig" "json" "json_schema"
        "jsr" "jsr_light" "julia" "jupyter" "just" "karma" "kcl" "key" "keystatic" "kivy" "kl"
        "knip" "kotlin" "kubernetes" "kusto" "label" "laravel" "latex" "latex-class"
        "latex-package" "latexmk" "lbx" "lean" "lefthook" "lerna" "less" "liara" "lib" "license"
        "lighthouse" "lilypond" "lintstaged" "liquid" "lisp" "livescript" "lock" "log" "lolcode"
        "lottie" "lua" "luau" "lynx" "lyric" "macaulay2" "makefile" "markdoc" "markdoc-config"
        "markdown" "markdownlint" "markojs" "mathematica" "matlab" "maven" "mdsvex" "mdx"
        "mercurial" "merlin" "mermaid" "meson" "metro" "minecraft" "minecraft-fabric" "mint"
        "mist" "mjml" "mocha" "modernizr" "mojo" "moon" "moonscript" "mrpack" "mxml"
        "nano-staged" "nano-staged_light" "ndst" "nest" "nest-controller" "nest-decorator"
        "nest-filter" "nest-gateway" "nest-guard" "nest-interceptor" "nest-middleware"
        "nest-module" "nest-pipe" "nest-resolver" "nest-service" "netlify" "netlify_light"
        "next" "next_light" "nginx" "ngrx-actions" "ngrx-effects" "ngrx-entity" "ngrx-reducer"
        "ngrx-selectors" "ngrx-state" "nim" "nix" "nodejs" "nodejs_alt" "nodemon" "npm" "nuget"
        "nunjucks" "nuxt" "nx" "objective-c" "objective-cpp" "ocaml" "odin" "onnx" "opa" "opam"
        "openapi" "openapi_light" "opencode" "opencode_light" "opentofu" "opentofu_light" "otne"
        "oxc" "packship" "palette" "panda" "parcel" "pascal" "pawn" "payload" "payload_light"
        "pdf" "pdm" "percy" "perl" "php" "php-cs-fixer" "php_elephant" "php_elephant_pink"
        "phpstan" "phpunit" "pinejs" "pipeline" "pkl" "plastic" "playwright" "plop"
        "pm2-ecosystem" "pnpm" "pnpm_light" "poetry" "postcss" "posthtml" "powerpoint"
        "powershell" "pre-commit" "prettier" "prisma" "processing" "prolog" "prompt" "proto"
        "protractor" "pug" "puppet" "puppeteer" "purescript" "python" "python-misc" "pytorch"
        "qsharp" "quarto" "quasar" "quokka" "qwik" "r" "racket" "raml" "razor" "rbxmk" "rc"
        "react" "react_ts" "readme" "reason" "red" "redux-action" "redux-reducer"
        "redux-selector" "redux-store" "regedit" "remark" "remix" "remix_light" "renovate"
        "replit" "rescript" "rescript-interface" "restql" "riot" "roadmap" "roblox" "robot"
        "robots" "rocket" "rojo" "rolldown" "rollup" "rome" "routing" "rspec" "rstack" "rubocop"
        "rubocop_light" "ruby" "ruff" "rust" "salesforce" "salt" "san" "sas" "sass" "sbt"
        "scala" "scheme" "scons" "scons_light" "screwdriver" "search" "semantic-release"
        "semantic-release_light" "semgrep" "sentry" "sequelize" "serverless" "settings" "shader"
        "shellcheck" "shellcheck_light" "silverstripe" "simulink" "siyuan" "sketch" "skill"
        "slim" "slint" "slug" "smarty" "sml" "snakemake" "snapcraft" "snowpack" "snowpack_light"
        "snyk" "solidity" "sonarcloud" "spwn" "stackblitz" "stan" "steadybit" "stencil"
        "stitches" "stitches_light" "storybook" "stryker" "sty" "stylable" "stylelint"
        "stylelint_light" "stylus" "sublime" "subtitles" "supabase" "svelte" "svelte_js"
        "svelte_ts" "svg" "svgo" "svgr" "swagger" "sway" "swc" "swift" "syncpack" "systemd"
        "systemd_light" "table" "tailwindcss" "tape" "taskfile" "tauri" "taze" "tcl" "teal"
        "templ" "template" "terraform" "test-js" "test-jsx" "test-ts" "tex" "textlint" "tilt"
        "tldraw" "tldraw_light" "tobi" "tobimake" "toc" "todo" "toml" "toml_light" "toon"
        "travis" "tree" "trigger" "tsconfig" "tsdoc" "tsdown" "tsil" "tune" "turborepo"
        "turborepo_light" "twig" "twine" "typedoc" "typescript" "typescript-def" "typst" "uiua"
        "umi" "uml" "uml_light" "unity" "unlicense" "unocss" "url" "uv" "vagrant" "vala"
        "vanilla-extract" "varnish" "vedic" "velite" "velocity" "vercel" "vercel_light"
        "verdaccio" "verified" "verilog" "verse" "verse_light" "vfl" "video" "vim" "virtual"
        "visualstudio" "vite" "vitest" "vlang" "vscode" "vue" "vue-config" "vuex-store"
        "wakatime" "wakatime_light" "wallaby" "wally" "warp" "warp_light" "watchman"
        "webassembly" "webhint" "webpack" "wepy" "werf" "windicss" "wolframlanguage" "word"
        "wrangler" "wxt" "xaml" "xmake" "xml" "yaml" "yang" "yarn" "zeabur" "zeabur_light" "zig"
        "zip"
    ],
};
