#include "db_object_dialogs.h"

#include <QCheckBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QFormLayout>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QInputDialog>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QLineEdit>
#include <QMessageBox>
#include <QPushButton>
#include <QTableWidget>
#include <QVBoxLayout>

namespace ui_shell {

namespace {

// Shows `ddlText` (already generated by `objectDdlPreview`) and asks for
// confirmation — every dialog's own "never run what the user has not
// seen" gate (`db_core::ddl`'s doc comment), one place rather than one
// copy per dialog.
bool confirmDdl(QWidget *parent, const QString &title, const QString &ddlText)
{
    return QMessageBox::question(parent, title,
                                 QObject::tr("Run this statement?\n\n%1").arg(ddlText))
      == QMessageBox::Yes;
}

// Preview → confirm → run, the one path every dialog below funnels its
// finished spec through. `kind` is `objectDdlPreview`/`runObjectDdl`'s own
// vocabulary (`ffi.rs`'s doc comment).
bool previewConfirmAndRun(QWidget *parent, DatabaseService *databaseService,
                          const QString &nodeId, const QString &kind, const QJsonObject &spec,
                          const QString &title)
{
    const QString specJson =
      QString::fromUtf8(QJsonDocument(spec).toJson(QJsonDocument::Compact));
    const FfiResult preview = databaseService->objectDdlPreview(nodeId, kind, specJson);
    if (preview.code != 0) {
        QMessageBox::warning(parent, title, QString(preview.message));
        return false;
    }
    if (!confirmDdl(parent, title, QString(preview.message))) {
        return false;
    }
    const FfiResult result = databaseService->runObjectDdl(nodeId, kind, specJson);
    if (result.code != 0) {
        QMessageBox::warning(parent, title, QString(result.message));
        return false;
    }
    return true;
}

// The Create/Modify Table dialog's own columns grid: Name / Type /
// Nullable / Default / Primary Key, with Add/Remove row buttons — shared
// by nothing else, so it lives inline here rather than its own header.
QTableWidget *buildColumnsGrid(QDialog *parent)
{
    auto *grid = new QTableWidget(0, 5, parent);
    grid->setHorizontalHeaderLabels(
      { QObject::tr("Name"), QObject::tr("Type"), QObject::tr("Nullable"), QObject::tr("Default"),
       QObject::tr("Primary Key") });
    grid->horizontalHeader()->setStretchLastSection(false);
    return grid;
}

void addColumnRow(QTableWidget *grid)
{
    const int row = grid->rowCount();
    grid->insertRow(row);
    grid->setItem(row, 0, new QTableWidgetItem());
    grid->setItem(row, 1, new QTableWidgetItem());
    auto *nullable = new QCheckBox();
    nullable->setChecked(true);
    grid->setCellWidget(row, 2, nullable);
    grid->setItem(row, 3, new QTableWidgetItem());
    grid->setCellWidget(row, 4, new QCheckBox());
}

// Reads `grid`'s rows into `db_core::ddl::ColumnSpec`-shaped JSON objects
// — a row with an empty name is skipped (the user removed it in spirit
// without removing the row).
QJsonArray columnsFromGrid(QTableWidget *grid)
{
    QJsonArray columns;
    for (int row = 0; row < grid->rowCount(); ++row) {
        const QString name = grid->item(row, 0) ? grid->item(row, 0)->text().trimmed() : QString();
        if (name.isEmpty()) {
            continue;
        }
        const QString type = grid->item(row, 1) ? grid->item(row, 1)->text().trimmed() : QString();
        const auto *nullable = qobject_cast<QCheckBox *>(grid->cellWidget(row, 2));
        const QString defaultText =
          grid->item(row, 3) ? grid->item(row, 3)->text().trimmed() : QString();
        const auto *primaryKey = qobject_cast<QCheckBox *>(grid->cellWidget(row, 4));
        QJsonObject column;
        column[QStringLiteral("name")] = name;
        column[QStringLiteral("type_name")] = type.isEmpty() ? QStringLiteral("TEXT") : type;
        column[QStringLiteral("nullable")] = nullable == nullptr || nullable->isChecked();
        if (!defaultText.isEmpty()) {
            column[QStringLiteral("default")] = defaultText;
        }
        column[QStringLiteral("primary_key")] = primaryKey != nullptr && primaryKey->isChecked();
        columns.append(column);
    }
    return columns;
}

} // namespace

bool showCreateTableDialog(QWidget *parent, DatabaseService *databaseService,
                           const QString &nodeId)
{
    QDialog dialog(parent);
    dialog.setWindowTitle(QObject::tr("Create Table"));
    auto *layout = new QVBoxLayout(&dialog);
    auto *form = new QFormLayout();
    auto *nameEdit = new QLineEdit(&dialog);
    form->addRow(QObject::tr("Table name:"), nameEdit);
    layout->addLayout(form);

    QTableWidget *grid = buildColumnsGrid(&dialog);
    addColumnRow(grid);
    layout->addWidget(grid, 1);

    auto *rowButtons = new QHBoxLayout();
    auto *addRowButton = new QPushButton(QObject::tr("Add Column"), &dialog);
    QObject::connect(addRowButton, &QPushButton::clicked, &dialog,
                     [grid]() { addColumnRow(grid); });
    rowButtons->addWidget(addRowButton);
    auto *removeRowButton = new QPushButton(QObject::tr("Remove Column"), &dialog);
    QObject::connect(removeRowButton, &QPushButton::clicked, &dialog, [grid]() {
        const int row = grid->currentRow();
        if (row >= 0) {
            grid->removeRow(row);
        }
    });
    rowButtons->addWidget(removeRowButton);
    rowButtons->addStretch(1);
    layout->addLayout(rowButtons);

    auto *buttons = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, &dialog);
    QObject::connect(buttons, &QDialogButtonBox::accepted, &dialog, &QDialog::accept);
    QObject::connect(buttons, &QDialogButtonBox::rejected, &dialog, &QDialog::reject);
    layout->addWidget(buttons);

    if (dialog.exec() != QDialog::Accepted || nameEdit->text().trimmed().isEmpty()) {
        return false;
    }
    QJsonObject spec;
    spec[QStringLiteral("name")] = nameEdit->text().trimmed();
    spec[QStringLiteral("columns")] = columnsFromGrid(grid);
    return previewConfirmAndRun(parent, databaseService, nodeId, QStringLiteral("create_table"),
                                spec, QObject::tr("Create Table"));
}

namespace {

// Add/Modify Column share the same form (name/type/nullable/default) —
// `modeTitle` picks the dialog's own title and which `db_core::ddl`
// generator kind it targets.
bool showColumnFormDialog(QWidget *parent, DatabaseService *databaseService,
                          const QString &nodeId, const QString &kind, const QString &title)
{
    QDialog dialog(parent);
    dialog.setWindowTitle(title);
    auto *layout = new QVBoxLayout(&dialog);
    auto *form = new QFormLayout();
    auto *nameEdit = new QLineEdit(&dialog);
    form->addRow(QObject::tr("Column name:"), nameEdit);
    auto *typeEdit = new QLineEdit(&dialog);
    form->addRow(QObject::tr("Type:"), typeEdit);
    auto *nullable = new QCheckBox(QObject::tr("Nullable"), &dialog);
    nullable->setChecked(true);
    form->addRow(QString(), nullable);
    auto *defaultEdit = new QLineEdit(&dialog);
    form->addRow(QObject::tr("Default (optional):"), defaultEdit);
    layout->addLayout(form);

    auto *buttons = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, &dialog);
    QObject::connect(buttons, &QDialogButtonBox::accepted, &dialog, &QDialog::accept);
    QObject::connect(buttons, &QDialogButtonBox::rejected, &dialog, &QDialog::reject);
    layout->addWidget(buttons);

    if (dialog.exec() != QDialog::Accepted || nameEdit->text().trimmed().isEmpty()
        || typeEdit->text().trimmed().isEmpty()) {
        return false;
    }
    QJsonObject spec;
    spec[QStringLiteral("name")] = nameEdit->text().trimmed();
    spec[QStringLiteral("type_name")] = typeEdit->text().trimmed();
    spec[QStringLiteral("nullable")] = nullable->isChecked();
    if (!defaultEdit->text().trimmed().isEmpty()) {
        spec[QStringLiteral("default")] = defaultEdit->text().trimmed();
    }
    return previewConfirmAndRun(parent, databaseService, nodeId, kind, spec, title);
}

} // namespace

bool showAddColumnDialog(QWidget *parent, DatabaseService *databaseService, const QString &nodeId)
{
    return showColumnFormDialog(parent, databaseService, nodeId, QStringLiteral("add_column"),
                                QObject::tr("Add Column"));
}

bool showModifyColumnDialog(QWidget *parent, DatabaseService *databaseService,
                            const QString &nodeId)
{
    return showColumnFormDialog(parent, databaseService, nodeId, QStringLiteral("alter_column"),
                                QObject::tr("Modify Column"));
}

bool showDropColumnDialog(QWidget *parent, DatabaseService *databaseService,
                         const QString &nodeId)
{
    bool ok = false;
    const QString column = QInputDialog::getText(parent, QObject::tr("Drop Column"),
                                                 QObject::tr("Column name:"), QLineEdit::Normal,
                                                 QString(), &ok);
    if (!ok || column.trimmed().isEmpty()) {
        return false;
    }
    QJsonObject spec;
    spec[QStringLiteral("column")] = column.trimmed();
    return previewConfirmAndRun(parent, databaseService, nodeId, QStringLiteral("drop_column"),
                                spec, QObject::tr("Drop Column"));
}

bool showCreateIndexDialog(QWidget *parent, DatabaseService *databaseService,
                          const QString &nodeId)
{
    QDialog dialog(parent);
    dialog.setWindowTitle(QObject::tr("Create Index"));
    auto *layout = new QVBoxLayout(&dialog);
    auto *form = new QFormLayout();
    auto *nameEdit = new QLineEdit(&dialog);
    form->addRow(QObject::tr("Index name:"), nameEdit);
    auto *columnsEdit = new QLineEdit(&dialog);
    columnsEdit->setPlaceholderText(QObject::tr("comma-separated column names"));
    form->addRow(QObject::tr("Columns:"), columnsEdit);
    auto *unique = new QCheckBox(QObject::tr("Unique"), &dialog);
    form->addRow(QString(), unique);
    layout->addLayout(form);

    auto *buttons = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, &dialog);
    QObject::connect(buttons, &QDialogButtonBox::accepted, &dialog, &QDialog::accept);
    QObject::connect(buttons, &QDialogButtonBox::rejected, &dialog, &QDialog::reject);
    layout->addWidget(buttons);

    if (dialog.exec() != QDialog::Accepted || nameEdit->text().trimmed().isEmpty()
        || columnsEdit->text().trimmed().isEmpty()) {
        return false;
    }
    QJsonArray columns;
    for (const QString &part : columnsEdit->text().split(QLatin1Char(','), Qt::SkipEmptyParts)) {
        columns.append(part.trimmed());
    }
    QJsonObject spec;
    spec[QStringLiteral("name")] = nameEdit->text().trimmed();
    // `table`/`schema` are resolved server-side from `nodeId` itself
    // (`DatabaseService::ddlContext`) and always overwrite whatever this
    // field carries — present only because `db_core::ddl::IndexSpec`
    // requires the JSON key to exist at all.
    spec[QStringLiteral("table")] = QString();
    spec[QStringLiteral("columns")] = columns;
    spec[QStringLiteral("unique")] = unique->isChecked();
    return previewConfirmAndRun(parent, databaseService, nodeId, QStringLiteral("create_index"),
                                spec, QObject::tr("Create Index"));
}

bool showCreateUserDialog(QWidget *parent, DatabaseService *databaseService,
                        const QString &nodeId)
{
    QDialog dialog(parent);
    dialog.setWindowTitle(QObject::tr("Create User"));
    auto *layout = new QVBoxLayout(&dialog);
    auto *form = new QFormLayout();
    auto *nameEdit = new QLineEdit(&dialog);
    form->addRow(QObject::tr("User name:"), nameEdit);
    auto *passwordEdit = new QLineEdit(&dialog);
    passwordEdit->setEchoMode(QLineEdit::Password);
    form->addRow(QObject::tr("Password:"), passwordEdit);
    auto *rolesEdit = new QLineEdit(&dialog);
    rolesEdit->setPlaceholderText(QObject::tr("comma-separated roles (Mongo only)"));
    form->addRow(QObject::tr("Roles:"), rolesEdit);
    layout->addLayout(form);

    auto *buttons = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, &dialog);
    QObject::connect(buttons, &QDialogButtonBox::accepted, &dialog, &QDialog::accept);
    QObject::connect(buttons, &QDialogButtonBox::rejected, &dialog, &QDialog::reject);
    layout->addWidget(buttons);

    if (dialog.exec() != QDialog::Accepted || nameEdit->text().trimmed().isEmpty()) {
        return false;
    }
    QJsonObject spec;
    spec[QStringLiteral("name")] = nameEdit->text().trimmed();
    if (!passwordEdit->text().isEmpty()) {
        spec[QStringLiteral("password")] = passwordEdit->text();
    }
    QJsonArray roles;
    for (const QString &part : rolesEdit->text().split(QLatin1Char(','), Qt::SkipEmptyParts)) {
        roles.append(part.trimmed());
    }
    spec[QStringLiteral("roles")] = roles;
    return previewConfirmAndRun(parent, databaseService, nodeId, QStringLiteral("create_user"),
                                spec, QObject::tr("Create User"));
}

} // namespace ui_shell
