//! Database Tools plan phase FX: the first `e2e_database` flow (database-
//! tools-plan.md §10's "budget 13/16" row) — a SQLite data source seeded
//! straight into the fixture project's `.ide/settings.toml` (no Add
//! Data Source dialog: the brief's own "prefer seeding, drive one dialog
//! only if cheap" call), the Database dock opened from the View menu,
//! the source connected (double-click, the same gesture
//! `e2e_containers.rs` uses for a `connection` row), its tree expanded
//! down to a column, and Go to DDL asserted against the opened `.sql`
//! tab's title and buffer text.
//!
//! Its own test binary for the reason every other `e2e_*.rs` file gives
//! (`e2e.rs` sits at its ratcheted size ceiling) — `make e2e`/`e2e-ci`
//! run it alongside the others.
//!
//! The fixture `.db` file is generated by this test with raw `rusqlite`
//! (a dev-dependency of `app`, not `db-drivers` — see `Cargo.toml`'s own
//! comment on that line for why): the *running app* is what exercises
//! `db_drivers::sqlite` end to end, this test process only needs to put
//! bytes on disk before it starts.

use std::path::{Path, PathBuf};

use e2e::{Ide, Mark};
use serde_json::Value;

const APP: &str = env!("CARGO_BIN_EXE_app");

fn rect_centre(rect: &Value) -> (i32, i32) {
    let r: Vec<i64> = rect
        .as_array()
        .expect("a rect array")
        .iter()
        .map(|v| v.as_i64().expect("a rect component"))
        .collect();
    ((r[0] + r[2] / 2) as i32, (r[1] + r[3] / 2) as i32)
}

/// A point inside a `database_tree_changed` row's own rect, near its
/// left edge rather than its centre.
///
/// `DatabasePanel::rowRectsJson` reports a row's rect as `QTreeWidget::
/// visualItemRect` returns it — spanning every column (Name *and*
/// Detail) — but the Database dock's `RightDockWidgetArea` slot is
/// narrower than that combined width, so the right portion of the
/// reported rect falls outside the actual window, and `rect_centre`
/// lands there instead of on the row. The left edge, where the row's own
/// label text is, does not have this problem — confirmed against
/// `debug-before-click.png`/`debug-after-click.png` while chasing this
/// down (kept as a comment here rather than the images themselves,
/// which this fix made unnecessary to keep).
fn rect_row_click_point(rect: &Value) -> (i32, i32) {
    let r: Vec<i64> = rect
        .as_array()
        .expect("a rect array")
        .iter()
        .map(|v| v.as_i64().expect("a rect component"))
        .collect();
    ((r[0] + 20) as i32, (r[1] + r[3] / 2) as i32)
}

/// Builds a fixture `.db` file with one table, then a fixture project
/// directory whose `.ide/settings.toml` names it as a `sqlite` data
/// source — returns both temp directories (both must outlive the running
/// `Ide`: the project one because `Ide::launch` copies *from* it, not
/// *of* it, so nothing there needs to survive the copy, but the db one
/// because the copied `settings.toml`'s `url` still points straight at
/// it).
fn fixture_project(name: &str) -> (tempfile::TempDir, tempfile::TempDir, PathBuf) {
    let db_dir = tempfile::TempDir::new().expect("db fixture dir");
    let db_path = db_dir.path().join("fixture.db");
    {
        let conn = rusqlite::Connection::open(&db_path).expect("creating the fixture db");
        conn.execute_batch(
            "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL); \
             INSERT INTO users (name) VALUES ('ada'), ('grace');",
        )
        .expect("seeding the fixture schema");
    }

    let project_dir = tempfile::TempDir::new().expect("fixture project dir");
    std::fs::create_dir_all(project_dir.path().join(".ide")).expect(".ide dir");
    std::fs::write(
        project_dir.path().join(".ide/settings.toml"),
        format!(
            "version = 1\n\n\
             [[database.sources]]\n\
             id = \"{name}\"\n\
             name = \"FX SQLite\"\n\
             driver = \"sqlite\"\n\
             url = {url}\n\
             auth = \"none\"\n",
            url = toml_string(&db_path),
        ),
    )
    .expect("writing settings.toml");

    (db_dir, project_dir, db_path)
}

/// A TOML basic string, quoted and escaped — the db path can contain
/// backslashes on some hosts (never on Linux, but this stays honest
/// rather than assuming forward slashes only).
fn toml_string(path: &Path) -> String {
    let raw = path.to_string_lossy();
    let escaped = raw.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// See `e2e_containers.rs`'s own `settle` for why this is needed: the
/// very first key sent after startup can be silently dropped, so one
/// settling click on the project tree's own row makes every key after it
/// land.
fn settle(ide: &Ide) {
    let row = ide
        .events()
        .into_iter()
        .rev()
        .find(|e| {
            e["ev"] == "project_tree_row"
                && e["path"].as_str().is_some_and(|p| p.ends_with("/.ide"))
        })
        .expect("the project tree reported its .ide row");
    let (x, y) = rect_centre(&row["rect"]);
    ide.click_at(x, y, 1);
    ide.focus_main();
}

/// Opens the dock and returns a fresh [`Mark`] taken right after the
/// click — never the mark the caller opened the View menu with. The
/// panel computes its tree once at startup (well before any project, let
/// alone this one, is open) and again off `DatabaseService::
/// projectOpened`, so a `database_tree_changed` marker with real rows
/// already exists long before the dock is ever shown; only a mark taken
/// after this click is guaranteed to skip both of those and see nothing
/// but `refreshE2eRects`'s own post-`visibilityChanged` report (the same
/// trap `e2e_containers.rs`'s own `open_containers_dock` doc comment
/// describes, except there the stale mark's rows are empty and a content
/// predicate alone can tell them apart — here they are not, so this waits
/// on position instead).
fn open_database_dock(ide: &Ide, mark: Mark) -> Mark {
    ide.key("alt+v"); // "&View"
    let item = ide.wait_for_event(mark, "the Database item in the View menu", |e| {
        e["ev"] == "view_menu_action" && e["label"] == "Database"
    });
    let (x, y) = rect_centre(&item["rect"]);
    let after_click = ide.mark(); // taken before the click: see this fn's own doc comment.
    ide.click_at(x, y, 1);
    ide.wait_for_event(after_click, "the database tree to be laid out", |e| {
        e["ev"] == "database_tree_changed"
            && e["rows"].as_array().is_some_and(|rows| !rows.is_empty())
    });
    after_click
}

fn find_row<'a>(rows: &'a [Value], kind: &str) -> Option<&'a Value> {
    rows.iter().find(|row| row["kind"] == kind)
}

fn wait_for_row(ide: &Ide, mark: Mark, kind: &str) -> Value {
    let kind = kind.to_string();
    let event = ide.wait_for_event(mark, &format!("a `{kind}` row in the database tree"), |e| {
        e["ev"] == "database_tree_changed"
            && e["rows"]
                .as_array()
                .is_some_and(|rows| find_row(rows, &kind).is_some())
    });
    find_row(event["rows"].as_array().expect("rows array"), &kind)
        .expect("just matched above")
        .clone()
}

#[test]
#[ignore = "E2E: needs an X server; run via `make e2e`"]
fn e2e_database_add_sqlite_source_and_browse_tree() {
    let name = "e2e_database_add_sqlite_source_and_browse_tree";
    let (_db_dir, project_dir, _db_path) = fixture_project(name);
    let mut ide = Ide::launch(name, APP, project_dir.path());
    ide.wait_for_ev(Mark::start(), "project_opened");
    settle(&ide);

    // The default, first-launch window is narrower than the docks
    // `main_window.cpp` lays out inside it assume (the Database dock's
    // two-column tree overflows its own `RightDockWidgetArea` slot at the
    // default size) — `window_maximized` (`e2e_panes.rs`'s own seed-then-
    // relaunch technique) is a flag the app only ever *observes*, never
    // actually enforces under bare Xvfb (no window manager to honour
    // `_NET_WM_STATE_MAXIMIZED`), so it does not help here. A direct
    // `xdotool windowsize` does: it is a plain `XResizeWindow` request,
    // which needs no window manager's cooperation at all.
    e2e::xdotool::run(&["windowsize", "--sync", ide.window(), "1600", "1200"]);

    let mark = ide.mark();
    let mark = open_database_dock(&ide, mark);

    // Connect: double-click the `source` row (`DatabasePanel::
    // onItemDoubleClicked`, the same gesture `e2e_containers.rs` uses for
    // its own `connection` rows). The source root defaults to expanded
    // (`DatabasePanel::rebuildTree`'s `row.depth == 0` default), so once
    // the post-connect Names introspect lands, its `users` table shows
    // without a separate expand click.
    let source = wait_for_row(&ide, mark, "source");
    let (sx, sy) = rect_row_click_point(&source["rect"]);
    ide.double_click_at(sx, sy, 1);
    ide.wait_for_event(mark, "the source to report connected", |e| {
        e["ev"] == "database_connection_state" && e["state"] == "connected"
    });

    // The default grouping is `ByObjectType` (`DatabaseService::flat`
    // starts `false`), so `users` sits inside a synthetic "Tables" folder
    // — a depth-1 row, not auto-expanded the way the depth-0 source root
    // is. Expand it before looking for the table row itself.
    let tables_folder = wait_for_row(&ide, mark, "folder-tables");
    let (fx, fy) = rect_row_click_point(&tables_folder["rect"]);
    ide.double_click_at(fx, fy, 1);
    let table = wait_for_row(&ide, mark, "table");

    // Expand the `users` table down to a column: `itemExpanded` re-
    // triggers `DatabaseService::expand`, a per-object Columns
    // introspect that reports back through `rows_changed`.
    let (tx, ty) = rect_row_click_point(&table["rect"]);
    ide.double_click_at(tx, ty, 1);
    ide.wait_for_event(mark, "a `column` row under `users`", |e| {
        e["ev"] == "database_tree_changed"
            && e["rows"]
                .as_array()
                .is_some_and(|rows| rows.iter().any(|r| r["kind"] == "column"))
    });

    // Go to DDL through the table row's context menu (no keymap shortcut
    // reaches the tree's own actions — `showContextMenu`'s own
    // `e2eMarkMenuActions` call is what makes this menu locatable).
    let table = wait_for_row(&ide, mark, "table");
    let (tx, ty) = rect_row_click_point(&table["rect"]);
    ide.click_at(tx, ty, 3); // right-click (xdotool button 3).
    let go_to_ddl = ide.wait_for_event(mark, "the Go to DDL context menu action", |e| {
        e["ev"] == "database_context_menu_action" && e["label"] == "Go to DDL"
    });
    let (gx, gy) = rect_centre(&go_to_ddl["rect"]);
    ide.click_at(gx, gy, 1);

    let tab = ide.wait_for_event(mark, "the DDL tab to open", |e| {
        e["ev"] == "tab_added" && e["title"].as_str().is_some_and(|t| t.ends_with(".sql"))
    });
    let title = tab["title"].as_str().expect("a title string");
    assert!(title.ends_with(".sql"), "DDL tab title was {title:?}");

    let tab_id = tab["tab_id"].as_u64().expect("a tab_id");
    let text = ide
        .mcp()
        .call("read_buffer", serde_json::json!({ "tab_id": tab_id }))["content"]
        .as_str()
        .expect("read_buffer returns a string")
        .to_string();
    assert!(
        text.to_uppercase().contains("CREATE TABLE"),
        "DDL buffer was: {text:?}"
    );

    assert_eq!(ide.quit(), 0);
}
